const data = [
  {
    id: 1,
    category: "Raki",
    origin_country: "Albania",
    name: "Skanderbeg",
  },
  {
    id: 2,
    category: "Wine",
    origin_country: "Andorra",
    name: "Gran Valira",
  },
  {
    id: 3,
    category: "Beer",
    origin_country: "Austria",
    name: "Stiegl",
  },
  {
    id: 4,
    category: "Vodka",
    origin_country: "Belarus",
    name: "Belaya Rus",
  },
  {
    id: 5,
    category: "Beer",
    origin_country: "Belgium",
    name: "Duvel",
  },
  {
    id: 6,
    category: "Rakija",
    origin_country: "Bosnia and Herzegovina",
    name: "Viljamovka",
  },
  {
    id: 7,
    category: "Rakia",
    origin_country: "Bulgaria",
    name: "Rakia",
  },
  {
    id: 8,
    category: "Rakija",
    origin_country: "Croatia",
    name: "Travarica",
  },
  {
    id: 9,
    category: "Commandaria",
    origin_country: "Cyprus",
    name: "Commandaria",
  },
  {
    id: 10,
    category: "Beer",
    origin_country: "Czech Republic",
    name: "Pilsner Urquell",
  },
  {
    id: 11,
    category: "Beer",
    origin_country: "Denmark",
    name: "Carlsberg",
  },
  {
    id: 12,
    category: "Beer",
    origin_country: "Estonia",
    name: "Saku",
  },
  {
    id: 13,
    category: "Beer",
    origin_country: "Finland",
    name: "Koff",
  },
  {
    id: 14,
    category: "Wine",
    origin_country: "France",
    name: "Champagne",
  },
  {
    id: 15,
    category: "Beer",
    origin_country: "Germany",
    name: "Oktoberfest Beer",
  },
  {
    id: 16,
    category: "Rakija",
    origin_country: "Greece",
    name: "Tsipouro",
  },
  {
    id: 17,
    category: "Beer",
    origin_country: "Hungary",
    name: "Soproni",
  },
  {
    id: 18,
    category: "Whiskey",
    origin_country: "Ireland",
    name: "Jameson",
  },
  {
    id: 19,
    category: "Wine",
    origin_country: "Italy",
    name: "Chianti",
  },
  {
    id: 20,
    category: "Beer",
    origin_country: "Latvia",
    name: "Aldaris",
  },
  {
    id: 21,
    category: "Beer",
    origin_country: "Lithuania",
    name: "Švyturys",
  },
  {
    id: 22,
    category: "Wine",
    origin_country: "Luxembourg",
    name: "Crémant",
  },
  {
    id: 23,
    category: "Wine",
    origin_country: "Malta",
    name: "Gellewza",
  },
  {
    id: 24,
    category: "Beer",
    origin_country: "Netherlands",
    name: "Heineken",
  },
  {
    id: 25,
    category: "Beer",
    origin_country: "Norway",
    name: "Ringnes",
  },
  {
    id: 26,
    category: "Beer",
    origin_country: "Poland",
    name: "Żywiec",
  },
  {
    id: 27,
    category: "Port Wine",
    origin_country: "Portugal",
    name: "Porto",
  },
  {
    id: 28,
    category: "Whiskey",
    origin_country: "Scotland",
    name: "Scotch Whisky",
  },
  {
    id: 29,
    category: "Beer",
    origin_country: "Slovakia",
    name: "Zlatý Bažant",
  },
  {
    id: 30,
    category: "Wine",
    origin_country: "Slovenia",
    name: "Rebula",
  },
  {
    id: 31,
    category: "Vodka",
    origin_country: "Sweden",
    name: "Absolut Vodka",
  },
  {
    id: 32,
    category: "Beer",
    origin_country: "Switzerland",
    name: "Feldschlösschen",
  },
  {
    id: 33,
    category: "Beer",
    origin_country: "United Kingdom",
    name: "Pale Ale",
  },
];

export default data;
